apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - name: master
          image: alfredocoj/jenkins-ci-master:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 50000
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          env:
#            - name: JENKINS_OPTS
#              valueFrom:
#                secretKeyRef:
#                  name: jenkins
#                  key: options
            - name: JAVA_OPTS
              value: '-Xmx1400m -Duser.timezone=America/Fortaleza'
            - name: JENKINS_JAVA_OPTIONS
              value: '-Dorg.apache.commons.jelly.tags.fmt.timeZone=America/Fortaleza -Duser.timezone=America/Fortaleza'
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: docker-sock-volume
              mountPath: /var/run/docker.sock
          resources:
            limits:
              cpu: 1000m
              memory: 4096Mi
            requests:
              cpu: 500m
              memory: 1024Mi
      terminationGracePeriodSeconds: 60
      nodeSelector:
        kubernetes.io/hostname: k8s-node-97
      volumes:
        - name: jenkins-home
          #emptyDir: {}
          hostPath:
            path: /jenkins
        - name: docker-sock-volume
          hostPath:
            path: /var/run/docker.sock
        #          persistentVolumeClaim:
        #            claimName: jenkins