#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: jenkins
#  namespace: jenkins
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: pd-standard # must match your storageclass from above
#  resources:
#    requests:
#      storage: 10Gi
#---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    type: local
spec:
  storageClassName: slow
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /jenkins